name: Nix Lint & Check

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix formatting
        run: nix run nixpkgs#nixpkgs-fmt -- --check .

      - name: Lint Nix files
        run: nix run nixpkgs#statix -- check .

      - name: Check flake (no build)
        run: nix flake check --no-build
